# Generated by Django 4.1 on 2022-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_instructor',
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
