# Generated by Django 4.1 on 2022-08-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlotInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_booked', models.IntegerField(default=0)),
                ('availablility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.availability')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.space')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='slots',
            field=models.ManyToManyField(through='booking.SlotInfo', to='booking.slot'),
        ),
        migrations.AddField(
            model_name='availability',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.space'),
        ),
    ]
