# Generated by Django 4.1 on 2022-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='slots',
            field=models.ManyToManyField(to='booking.slot'),
        ),
        migrations.AddField(
            model_name='availability',
            name='slots',
            field=models.ManyToManyField(to='booking.slot'),
        ),
    ]
