# Generated by Django 4.1 on 2022-08-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_space_assoc_sport'),
        ('booking', '0002_alter_availability_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='slots',
            field=models.ManyToManyField(through='booking.SlotInfo', to='booking.slot'),
        ),
        migrations.AddField(
            model_name='availability',
            name='slots',
            field=models.ManyToManyField(through='booking.SlotInfo', to='booking.slot'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.space'),
        ),
    ]
