# Generated by Django 4.1 on 2022-08-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_availability_slots_alter_availability_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotinfo',
            name='no_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='slotInfoObj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.slotinfo'),
        ),
        migrations.AddField(
            model_name='slotinfo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
