# Generated by Django 4.1 on 2022-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_slotinfo_no_booked_booking_slotinfoobj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotinfo',
            name='bookings',
            field=models.ManyToManyField(to='booking.booking'),
        ),
    ]
