# Generated by Django 4.1 on 2022-08-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_slotinfo_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotinfo',
            name='bookings',
        ),
    ]
