# Generated by Django 4.1 on 2022-08-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_slotinfo_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotinfo',
            old_name='availablility',
            new_name='availability',
        ),
    ]
