# Generated by Django 4.1 on 2022-09-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_space_assoc_sport'),
        ('booking', '0007_rename_availablility_slotinfo_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slotInfoObj',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.slot'),
        ),
        migrations.AddField(
            model_name='availability',
            name='units_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='availability',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.space'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('space', 'slot', 'date')},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='slots',
        ),
        migrations.DeleteModel(
            name='SlotInfo',
        ),
    ]
