# Generated by Django 4.1 on 2022-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='sport',
            new_name='assoc_sport',
        ),
        migrations.AlterField(
            model_name='sport',
            name='accepting_bookings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name of the Sport'),
        ),
    ]
