# Generated by Django 4.1 on 2022-08-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_rename_sport_space_assoc_sport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='accepting_bookings',
            new_name='available',
        ),
    ]
