# Generated by Django 4.1 on 2022-08-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_rename_accepting_bookings_space_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='name',
            new_name='sport_name',
        ),
    ]
