# Generated by Django 4.1 on 2022-08-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_remove_space_assoc_sport_delete_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=20, verbose_name='Name of the Sport')),
                ('accepting_bookings', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='assoc_sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
    ]
