# Generated by Django 4.1 on 2022-08-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_sport_space_assoc_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='assoc_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
    ]
