# Generated by Django 4.1 on 2022-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_slotinfoobj_availability_date_and_more'),
        ('sports', '0007_alter_space_assoc_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='slots',
            field=models.ManyToManyField(through='booking.Availability', to='booking.slot'),
        ),
    ]
