# Generated by Django 4.1 on 2022-09-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_request_remove_booking_space_booking_availability_and_more'),
        ('sports', '0009_alter_space_assoc_sport_alter_space_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Space',
        ),
    ]
